ekf_filter_node:
  ros__parameters:      
    frequency: 1000.0  # Frequency in Hz at which the filter will run

    # Set to true if you are operating in a planar environment
    two_d_mode: false

    # Sensor configurations
    odom0: /hslam_data  # Topic name for SLAM data
    odom0_config: [true, true, true,  # Use x, y, z position data
                  false, false, false,  # Ignore roll, pitch, yaw orientation data
                  false, false, false,  # Ignore x, y, z linear velocity data
                  false, false, false,  # Ignore roll, pitch, yaw angular velocity data
                  false, false, false]  # Ignore linear acceleration data

    odom0_queue_size: 2  # The queue size for incoming odometry messages.
    odom0_nodelay: false  # Whether to allow the filter to process messages out of order.
    odom0_differential: false  # Whether to treat the odometry data as differential (relative changes) instead of absolute values.
    odom0_relative: false  # Whether to treat the odometry data as relative to the robot's starting position.
    # odom0_pose_covariance: [0.1, 0.0, 0.0, 0.0, 0.0, 0.0,
    #                         0.0, 0.1, 0.0, 0.0, 0.0, 0.0,
    #                         0.0, 0.0, 0.1, 0.0, 0.0, 0.0,
    #                         0.0, 0.0, 0.0, 0.1, 0.0, 0.0,
    #                         0.0, 0.0, 0.0, 0.0, 0.1, 0.0,
    #                         0.0, 0.0, 0.0, 0.0, 0.0, 1.0]

    gps0: /gps_data  # Topic name for GPS data
    gps0_config: [true, true, true,  # Use latitude, longitude, altitude data
                  false, false, false,  # Ignore orientation data
                  false, false, false,  # Ignore linear velocity data
                  false, false, false,  # Ignore angular velocity data
                  false, false, false]  # Ignore linear acceleration data

    gps0_queue_size: 2  # The queue size for incoming GPS messages.
    gps0_nodelay: false  # Whether to allow the filter to process messages out of order.
    gps0_differential: false  # Whether to treat the GPS data as differential (relative changes) instead of absolute values.
    gps0_relative: false  # Whether to treat the GPS data as relative to the robot's starting position.

    # imu0: /imu  # Topic name for IMU data (if available)
    # imu0_config: [false, false, false,  # Ignore orientation data
    #               false, false, false,  # Ignore angular velocity data
    #               false, false, false,  # Ignore linear velocity data
    #               false, false, false,  # Ignore angular velocity data
    #               false, false, false]  # Ignore linear acceleration data
    # imu0_queue_size: 5  # The queue size for incoming IMU messages.
    # imu0_nodelay: false  # Whether to allow the filter to process messages out of order.
    # imu0_differential: false  # Whether to treat the IMU data as differential (relative changes) instead of absolute values.
    # imu0_relative: false  # Whether to treat the IMU data as relative to the robot's starting position.
    # imu0_remove_gravitational_acceleration: false  # Whether to remove the gravitational acceleration component from the IMU data.

    # Other settings
    use_control: false
    stamped_control: false
    control_timeout: 0.2
    print_diagnostics: true

    # Initial state (if known, otherwise leave commented out)
    # initial_state: [x, y, z, roll, pitch, yaw, vx, vy, vz, vroll, vpitch, vyaw]
